### ISSUE TITLE
Help with docker setup - slave machine

### ISSUE THREAD

**Issue by jay0129** [DeviceFarmer/stf#104]
**What is the issue or idea you have?**
I have a dockerized setup using the script from [stf-poc](https://github.com/nikosch86/stf-poc) on a machineA
I am trying to attach machineB to machineA, but I am having trouble, please help me.

Here are my questions:
1. Is it enough to just run or install `stf-provider` and `adb` on machineB?
2. For the command `stf provider` from machineB, should I pass `--public-ip` with machineA's IP or machineB's IP?
3. For the command `stf provider` from machineB, should I pass `screen-ws-url-pattern` with machineA's IP and stations name?
4. STF is already running on machineA, should I restart machineA after attaching machineB to it? I am wondering the sequence of these kinds of operations
**Please provide the steps to reproduce the issue.**

**nginx.conf on machineA:**
```
    location ~ "^/d/machineA/([^/]+)/(?<port>[0-9]{3,5})/$" {
      proxy_pass http://provider:$port/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ "^/d/machineB/([^/]+)/(?<port>[0-9]{5})/$" {
      proxy_pass http://${MACHINE_B_IP}:$port/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Real-IP $remote_addr;
    }
```
For more information, you can see full nginx.conf [here](https://github.com/nikosch86/stf-poc/blob/master/nginx/nginx.conf)

**docker-compose.yml on machineA:**

> Same as [here](https://github.com/nikosch86/stf-poc/blob/master/docker-compose.yml) with few changes including auth-ldap

**docker-compose.yml on machineB:**
```
version: '3'

volumes:
  storage-temp:

services:
  adb:
    image: sorccu/adb:latest
    restart: unless-stopped
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
  provider:
    image: ${STF_IMAGE}
    restart: unless-stopped
    environment:
      - STF_ADMIN_NAME
      - STF_ADMIN_EMAIL
    command: stf provider --name ${STATION_NAME} --connect-sub tcp://${MACHINE_A_IP}:7250 --connect-push tcp://${MACHINE_A_IP}:7270 --storage-url http://${APP_IP}/ --public-ip ${MACHINE_B_IP} --heartbeat-interval 10000 --screen-ws-url-pattern "ws://${MACHINE_A_IP}/d/${STATION_NAME}/<%= serial %>/<%= publicPort %>/" --adb-host adb --min-port 7400 --max-port 7700
    ports:
      - 7400-7700:7400-7700
    depends_on:
      - adb
```
**nginx.conf on machineB:**
There is no nginx.conf on machineB
