### ISSUE TITLE
Support Android 11

### ISSUE THREAD

**Issue by jay0129** [DeviceFarmer/stf#110]
**Is your feature request related to a problem? Please describe.**
I started STF server by using docker-compose file like this [compose file](https://github.com/nikosch86/stf-poc/blob/master/docker-compose.yml).
Other devices were connected to STF.
Pixel3 (11) cannot connected to STF, even though it is connected to ADB

**Describe the solution you'd like**
Support Android 11 OS

**Additional context**
_lsusb_
`Bus 001 Device 058: ID 18d1:4ee2 Google Inc. Nexus Device (debug)`

_adb --version (Trial 1 - sorccu/adb:latest)_
```
Android Debug Bridge version 1.0.39
Version 0.0.1-4500957
Installed as /opt/platform-tools/adb
```
_adb --version (Trial 2 - I updated it to use docker image from "devicefarmer/adb:latest")_
```
Android Debug Bridge version 1.0.41
Version 29.0.6-6198805
Installed as /opt/platform-tools/adb
```
_stf doctor (from stf app container)_
```
2020-09-25T02:40:44.439Z INF/cli:doctor 20 [*] OS Arch: x64
2020-09-25T02:40:44.441Z INF/cli:doctor 20 [*] OS Platform: linux
2020-09-25T02:40:44.441Z INF/cli:doctor 20 [*] OS Platform: 5.4.0-47-generic
2020-09-25T02:40:44.441Z INF/cli:doctor 20 [*] Using Node 8.9.3
2020-09-25T02:40:44.449Z INF/cli:doctor 20 [*] Using ZeroMQ 4.1.4
2020-09-25T02:40:44.459Z ERR/cli:doctor 20 [*] RethinkDB is not installed (`rethinkdb` is missing)
2020-09-25T02:40:44.459Z ERR/cli:doctor 20 [*] ProtoBuf is not installed (`protoc` is missing)
2020-09-25T02:40:44.459Z ERR/cli:doctor 20 [*] ADB is not installed (`adb` is missing)
2020-09-25T02:40:44.499Z INF/cli:doctor 20 [*] Using GraphicsMagick 1.3.23
```

**Comment by koral--** [comment]
https://github.com/nikosch86/stf-poc/blob/master/docker-compose.yml#L35
It uses `openstf/stf`. This project is `devicefarmer/stf`.
Please also switch other dependencies to `devicefarmer` namespace.
Add a comment if issue persists on `devicefarmer` so issue may be reopened.

**Comment by jay0129** [comment]
Sorry for the wrong configuration.
I actually used `devicefarmer/stf` and Android11 device (Pixel3) disconnected after `Preparing`.
Here are my files.

docker-compose.yml
```
version: '3'

volumes:
  rethinkdb:
  storage-temp:

services:
  nginx:
    build: nginx/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - app
      - auth
      - storage-plugin-apk
      - storage-plugin-image
      - storage-temp
      - websocket
      - api
  adb:
    image: ${ADB_IMAGE}
    restart: unless-stopped
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
  rethinkdb:
    image: ${RETHINKDB_IMAGE}
    restart: unless-stopped
    environment:
      - STF_ADMIN_NAME
      - STF_ADMIN_EMAIL
    volumes:
      - rethinkdb:/data
    command: rethinkdb --bind all
    ports:
      - 8080:8080
  app:
    image: ${STF_IMAGE}
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
      - STF_ADMIN_NAME
      - STF_ADMIN_EMAIL
    command: stf app --auth-url http://${PUBLIC_IP}/auth/ldap/ --websocket-url ws://${PUBLIC_IP}/ --port 3000
    depends_on:
      - rethinkdb
      - auth
      - websocket
  auth:
    image: ${STF_IMAGE}
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
      - STF_ADMIN_NAME
      - STF_ADMIN_EMAIL
      - NODE_TLS_REJECT_UNAUTHORIZED
    command: stf auth-ldap --app-url http://${PUBLIC_IP}/ --port 3000 --ldap-url "ldap://ldap.linecorp.com:22389" --ldap-search-dn "OU=user,OU=NAVER,DC=navercorp,DC=com" --ldap-bind-credentials ${LDAP_PASSWORD} --ldap-bind-dn "cn=nhnauth" --ldap-search-field "name"
    depends_on:
      - rethinkdb
  processor:
    image: ${STF_IMAGE}
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - STF_ADMIN_NAME
      - STF_ADMIN_EMAIL
    command: stf processor --connect-app-dealer tcp://triproxy:7160 --connect-dev-dealer tcp://dev-triproxy:7260
    depends_on:
      - rethinkdb
      - triproxy
      - dev-triproxy
  triproxy:
    image: ${STF_IMAGE}
    restart: unless-stopped
    command: stf triproxy app --bind-pub "tcp://*:7150" --bind-dealer "tcp://*:7160" --bind-pull "tcp://*:7170"
  dev-triproxy:
    image: ${STF_IMAGE}
    restart: unless-stopped
    command: stf triproxy dev --bind-pub "tcp://*:7250" --bind-dealer "tcp://*:7260" --bind-pull "tcp://*:7270"
    ports:
      - 7250:7250
      - 7260:7260
      - 7270:7270
  migrate:
    image: ${STF_IMAGE}
    environment:
      - RETHINKDB_PORT_28015_TCP
      - STF_ROOT_GROUP_NAME
      - STF_ADMIN_NAME
      - STF_ADMIN_EMAIL
    command: stf migrate
    depends_on:
      - rethinkdb
  provider:
    image: ${STF_IMAGE}
    restart: unless-stopped
    environment:
      - STF_ADMIN_NAME
      - STF_ADMIN_EMAIL
    command: stf provider --name ${STATION_NAME} --connect-sub tcp://dev-triproxy:7250 --connect-push tcp://dev-triproxy:7270 --storage-url http://${PUBLIC_IP}/ --public-ip ${PUBLIC_IP} --heartbeat-interval 10000 --screen-ws-url-pattern "ws://${PUBLIC_IP}/d/${STATION_NAME}/<%= serial %>/<%= publicPort %>/" --adb-host adb --min-port 7400 --max-port 7700 --allow-remote
    ports:
      - 7400-7700:7400-7700
    depends_on:
      - adb
      - dev-triproxy
      - triproxy
      - storage-temp
  reaper:
    image: ${STF_IMAGE}
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
    depends_on:
      - migrate
      - rethinkdb
      - dev-triproxy
      - triproxy
    command: stf reaper dev --connect-push tcp://dev-triproxy:7270 --connect-sub tcp://triproxy:7150 --heartbeat-timeout 30000
  storage-plugin-apk:
    image: ${STF_IMAGE}
    restart: unless-stopped
    environment:
      - STF_ADMIN_NAME
      - STF_ADMIN_EMAIL
    command: stf storage-plugin-apk --port 3000 --storage-url http://${PUBLIC_IP}/
    depends_on:
      - storage-temp
  storage-plugin-image:
    image: ${STF_IMAGE}
    restart: unless-stopped
    environment:
      - STF_ADMIN_NAME
      - STF_ADMIN_EMAIL
    command: stf storage-plugin-image --port 3000 --storage-url http://${PUBLIC_IP}/
    depends_on:
      - storage-temp
  storage-temp:
    build: storage-temp/
    restart: unless-stopped
    volumes:
      - storage-temp:/app/data
    command: stf storage-temp --port 3000 --save-dir /app/data
  websocket:
    image: ${STF_IMAGE}
    restart: unless-stopped
    environment:
      - SECRET
      - RETHINKDB_PORT_28015_TCP
      - STF_ADMIN_NAME
      - STF_ADMIN_EMAIL
    command: stf websocket --port 3000 --storage-url http://${PUBLIC_IP}/ --connect-sub tcp://triproxy:7150 --connect-push tcp://triproxy:7170
    depends_on:
      - migrate
      - rethinkdb
      - storage-temp
      - triproxy
      - dev-triproxy
  api:
    image: ${STF_IMAGE}
    restart: unless-stopped
    environment:
      - SECRET
      - RETHINKDB_PORT_28015_TCP
    command: stf api --port 3000 --connect-sub tcp://triproxy:7150 --connect-push tcp://triproxy:7170 --connect-sub-dev tcp://dev-triproxy:7250 --connect-push-dev tcp://dev-triproxy:7270
    depends_on:
      - migrate
      - rethinkdb
      - triproxy
```

.env
```
PUBLIC_IP=xxx
SECRET=xxx
RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
STATION_NAME=xxx
STF_ROOT_GROUP_NAME=xxx
STF_ADMIN_NAME=xxx
STF_ADMIN_EMAIL=xxx
NODE_TLS_REJECT_UNAUTHORIZED=0
LDAP_PASSWORD=xxx
STF_IMAGE=devicefarmer/stf:latest
RETHINKDB_IMAGE=rethinkdb:2.4
ADB_IMAGE=devicefarmer/adb:latest
```
