### ISSUE TITLE
Need help with ldap authorization

### ISSUE THREAD

**Issue by ababushkin-bscmsc** [DeviceFarmer/stf#167]
**What is the issue or idea you have?**

Is there a clear instruction for configuring ldap authorization? Can't figure out how to pass parameters
Can I have a command line example?
For example: stf local public-ip 10.10.10.10 --auth-type ldap --auth-options '[--app-url' http://example.com ', ldap-url' ldap: //example.com: 389 ']' and so on
I would like to see the most common example

**Comment by ababushkin-bscmsc** [comment]
i am using stf local --public-ip 10.2.7.18 --auth-type ldap --auth-options '["--app-url","http://10.2.7.18:7100","--ldap-bind-dn","OU=SERVICES,OU=BSC,DC=bscmsc,DC=ru","--ldap-search-class","top;organizationalUnit","--ldap-search-dn",DC=bscmsc,DC=ru","--ldap-search-field","sAMAccountName","--ldap-url","ldap://10.2.8.9:389"]'

I get in the logs:
2021-01-12T12:47:58.422Z INF/util:procutil 1670 [*] Forking "/home/stf/stf/lib/cli provider --name app-test --min-port 7400 --max-port 7700 --connect-sub tcp://127.0.0.1:7114 --connect-push tcp://127.0.0.1:7116 --group-timeout 900 --public-ip 10.2.7.18 --storage-url http://localhost:7100/ --adb-host 127.0.0.1 --adb-port 5037 --vnc-initial-size 600x800 --mute-master never"
/home/stf/stf/node_modules/bluebird/js/main/promise.js:680
            throw e;
            ^

SyntaxError: Unexpected token D in JSON at position 161
    at JSON.parse (<anonymous>)
    at run (/home/stf/stf/lib/cli/local/index.js:308:23)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Object.module.exports.handler (/home/stf/stf/lib/cli/local/index.js:441:6)
    at Object.self.runCommand (/home/stf/stf/node_modules/yargs/lib/command.js:170:22)
    at parseArgs (/home/stf/stf/node_modules/yargs/yargs.js:920:28)
    at Object.get [as argv] (/home/stf/stf/node_modules/yargs/yargs.js:860:16)
    at Object.<anonymous> (/home/stf/stf/lib/cli/index.js:47:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/stf/stf/lib/cli/please.js:2:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)

**Comment by timansky** [comment]
env example:
```
  STF_AUTH_LDAP_APP_URL: /
  STF_AUTH_LDAP_LDAP_URL: ldap://ldap.server
  STF_AUTH_LDAP_LDAP_BIND_CREDENTIALS: password
  STF_AUTH_LDAP_LDAP_BIND_DN: cn=dsa-stf,ou=dsa,dc=domain,dc=local
  STF_AUTH_LDAP_LDAP_SEARCH_DN: ou=people,dc=domain,dc=local
  STF_AUTH_LDAP_LDAP_SEARCH_FIELD: uid
  STF_AUTH_LDAP_LDAP_SEARCH_CLASS: inetOrgPerson
  STF_AUTH_LDAP_LDAP_USERNAME_FIELD: uid
```

also you need ldap provider running
k8s example:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stf-server-app
  namespace: stf
  labels:
    blabla.service.name: stf-server
spec:
  selector:
    matchLabels:
      blabla.service.name: stf-server
  replicas: 1
  template:
    metadata:
      labels:
        blabla.service.name: stf-server
    spec:
      containers:
        - name: app
          image: devicefarmer/stf:3.5.0
          command:
            - stf
          args:
            - app
          envFrom:
            - configMapRef:
                name: stf-server
          resources:
            limits:
              memory: "128Mi"
              cpu: "1"
            requests:
              memory: "64Mi"
              cpu: "0.1"
          livenessProbe:
            tcpSocket:
              port: 7105
        - name: websocket
          image: devicefarmer/stf:3.5.0
          command:
            - stf
          args:
            - websocket
          envFrom:
            - configMapRef:
                name: stf-server
          resources:
            limits:
              memory: "128Mi"
              cpu: "1"
            requests:
              memory: "64Mi"
              cpu: "0.1"
          livenessProbe:
            tcpSocket:
              port: 7110
        - name: auth
          image: devicefarmer/stf:3.5.0
          command:
            - stf
          args:
            - auth-ldap
          envFrom:
            - configMapRef:
                name: stf-server
          resources:
            limits:
              memory: "128Mi"
              cpu: "1"
            requests:
              memory: "64Mi"
              cpu: "0.1"
          livenessProbe:
              tcpSocket:
                port: 7120
        - name: reaper
          image: devicefarmer/stf:3.5.0
          command:
            - stf
          args:
            - reaper
          envFrom:
            - configMapRef:
                name: stf-server
          resources:
            limits:
              memory: "64Mi"
              cpu: "1"
            requests:
              memory: "32Mi"
              cpu: "0.1"
          livenessProbe:
              tcpSocket:
                port: 7120
```
