### ISSUE TITLE
docker-compose for Ubuntu

### ISSUE THREAD

**Issue by mhaqqiw** [DeviceFarmer/stf#56]
Is there any docker-compose for this STF?

**Comment by koral--** [comment]
Not yet.

**Comment by jay0129** [comment]
@mhaqqiw I found one here:
https://github.com/nikosch86/stf-poc

**Comment by gounthar** [comment]
Is it still valid?
Are there variants for the standalone, App only, and Provider only?
Thanks.

**Comment by lanrat** [comment]
This is the standalone STF docker-compose file I use: 

```yaml
version: "3"

services:
  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb:2.3
    restart: unless-stopped
    volumes:
        - "rethinkdb-data:/data"
    command: "rethinkdb --bind all --cache-size 2048"

  adb:
    container_name: adb
    image: sorccu/adb:latest
    restart: unless-stopped
    volumes: 
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true

  stf:
    container_name: stf
    image: devicefarmer/stf
    ports:
      - "7100:7100"
        #- "7105:7105"
      - "7110:7110"
        #- "7120:7120"
      - "7400-7500:7400-7500"
    environment:
      - TZ='America/Los_Angeles'
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=YOUR_EMAIL
      - STF_ADMIN_NAME=YOUR_NAME
    restart: unless-stopped
    command: stf local --adb-host adb --public-ip YOUR_IP --provider-min-port 7400 --provider-max-port 7500

volumes:
  rethinkdb-data: {}
```

Replace the placeholders in caps and it should work for small setups.

It would be nice if STF could use relative links for everything so that there is no need to pass `--public-ip` as it should not really matter....
