### ISSUE TITLE
STF device Providing all 0 of 1 device(s); ignoring "R3CT80EWPZB"

### ISSUE THREAD

**Issue by namilkimfree** [DeviceFarmer/stf#602]
**What is the issue or idea you have?**

provider found  my device, but ignoring.

stf-provider_1  | 2022-10-21T02:01:07.018Z INF/provider 1 [*] Subscribing to permanent channel "ubY6FvEQT+G3ZIRt7TwbcA=="
stf-provider_1  | 2022-10-21T02:01:07.023Z INF/provider 1 [*] Sending output to "tcp://devside.my.stf.com:7270"
stf-provider_1  | 2022-10-21T02:01:07.023Z INF/provider 1 [*] Receiving input from "tcp://devside.my.stf.com:7250"
stf-provider_1  | 2022-10-21T02:01:07.026Z INF/provider 1 [*] Tracking devices
stf-provider_1  | 2022-10-21T02:01:07.027Z INF/provider 1 [*] Found device "R3CT80EWPZB" (device)
stf-provider_1  | 2022-10-21T02:01:17.031Z INF/provider 1 [*] Providing all 0 of 1 device(s); ignoring "R3CT80EWPZB"

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

root@NM-P2106006:/stf_app# adb devices -l
List of devices attached
R3CT80EWPZB            device usb:1-1 product:b4qksx model:SM_F721N device:b4q transport_id:1

**Please provide the steps to reproduce the issue.**

windows 10 wsl ubuntu 18.04 lts

server and provider same machine

.env file:

```
STF_HOST=my.stf.com
STF_URL=http://my.stf.com
STF_IMAGE=devicefarmer/stf:latest
STF_PROVIDER=provider1
STF_SECRET= mystf

```

server:  A IP

docker-compose:

```

version: '3'
services:
  nginx:
    image: nginx:1.15.7-alpine
    volumes:
      - /data/stf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: "host"

  rethinkdb:
    depends_on:
      - nginx
    image: rethinkdb:2.3.6
    command: rethinkdb --bind all --cache-size 8192 --http-port 8090 --no-update-check
    volumes:
      - /data/stf/rethinkdb:/data
    network_mode: "host"

  stf-migrate:
    depends_on:
      - rethinkdb
    image: $STF_IMAGE
    command: stf migrate
    network_mode: "host"

  stf-app:
    depends_on:
      - stf-migrate
    image: $STF_IMAGE
    command: stf app --port 3100 --auth-url ${STF_URL}/auth/mock/ --websocket-url ws://${STF_HOST}/
    network_mode: "host"
    environment:
      SECRET: $STF_SECRET

  stf-auth:
    depends_on:
      - stf-app
    image: $STF_IMAGE
    command: stf auth-mock --port 3101 --app-url ${STF_URL}
    network_mode: "host"
    environment:
      SECRET: $STF_SECRET

  stf-storage-plugin-apk:
    depends_on:
      - stf-api
    image: $STF_IMAGE
    command: stf storage-plugin-apk --port 3102 --storage-url ${STF_URL}
    network_mode: "host"

  stf-storage-plugin-image:
    depends_on:
      - stf-storage-plugin-apk
    image: $STF_IMAGE
    command: stf storage-plugin-image --port 3103 --storage-url $STF_URL
    network_mode: "host"

  stf-storage-temp:
    depends_on:
      - stf-storage-plugin-image
    image: $STF_IMAGE
    command: stf storage-temp --port 3104 --save-dir /tmp
    network_mode: "host"

  stf-websocket:
    depends_on:
      - stf-auth
    image: $STF_IMAGE
    command: stf websocket --port 3105 --storage-url $STF_URL --connect-sub tcp://$STF_HOST:7150 --connect-push tcp://$STF_HOST:7170
    network_mode: "host"
    environment:
      SECRET: $STF_SECRET

  stf-api:
    depends_on:
      - stf-websocket
    image: $STF_IMAGE
    command: stf api --port 3106 --connect-sub tcp://$STF_HOST:7150 --connect-push tcp://$STF_HOST:7170  --connect-sub-dev tcp://devside.$STF_HOST:7250 --connect-push-dev tcp://devside.$STF_HOST:7270
    network_mode: "host"
    environment:
      SECRET: $STF_SECRET

  stf-triproxy-app:
    depends_on:
      - stf-storage-temp
    image: $STF_IMAGE
    command: stf triproxy app --bind-pub "tcp://*:7150" --bind-dealer "tcp://*:7160" --bind-pull "tcp://*:7170"
    network_mode: "host"

  stf-processor:
    depends_on:
      - stf-triproxy-app
    image: $STF_IMAGE
    command: stf processor stf-processer --connect-app-dealer tcp://$STF_HOST:7160 --connect-dev-dealer tcp://$STF_HOST:7260
    network_mode: "host"

  stf-triproxy-dev:
    depends_on:
      - stf-processor
    image: $STF_IMAGE
    command: stf triproxy dev --bind-pub "tcp://*:7250" --bind-dealer "tcp://*:7260" --bind-pull "tcp://*:7270"
    network_mode: "host"

  stf-reaper:
    depends_on:
      - stf-triproxy-dev
    image: $STF_IMAGE
    command: stf reaper dev --connect-push tcp://$STF_HOST:7270 --connect-sub tcp://$STF_HOST:7150 --heartbeat-timeout 30000
    network_mode: "host"

  stf-log-rethinkdb:
    depends_on:
      - stf-reaper
    image: $STF_IMAGE
    command: stf log-rethinkdb --connect-sub tcp://devside.$STF_HOST:7150
    network_mode: "host"

  swagger-ui:
          volumes:
                  - /data/stf/swagger/api_v1.yaml:/swagger.yaml
          image: swaggerapi/swagger-ui
          network_mode: "host"
          environment:
                  VALIDATOR_URL: null
                  SWAGGER_JSON: "/swagger.yaml"
          ports:
                  - "8080"

```

provider: A IP

docker-compose:

```
services:

  stf-provider:
    image: $STF_IMAGE
    command: stf provider --name "${STF_PROVIDER}" --connect-sub tcp://devside.$STF_HOST:7250 --connect-push tcp://devside.$STF_HOST:7270 --storage-url $STF_URL --public-ip $STF_PROVIDER.$STF_HOST --min-port=15000 --max-port=25000 --heartbeat-interval 20000 --screen-ws-url-pattern "ws://${STF_HOST}/d/${STF_PROVIDER}/<%= serial %>/<%= publicPort %>/"
    network_mode: "host"
    privileged: true

```

docker-compose 

**What is the expected behavior?**

attached my device Z Flip 4

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

server app
![image](https://user-images.githubusercontent.com/44854923/197095765-32f0a181-0404-44ff-9a62-eee7e528e2ee.png)

provider
![image](https://user-images.githubusercontent.com/44854923/197095909-d958b92b-a06d-4e75-90d9-a8b6216cd2f6.png)

**Please run `stf doctor` and paste the output here.**
