### ISSUE TITLE
In Server/Node setup, device in WebGUIs device list are accessible, but not usable (grey screen) after network disconnect

### ISSUE THREAD

**Issue by ConfusedMerlin** [DeviceFarmer/stf#623]
**What is the issue or idea you have?**

A Server Node Setup, where the Server runs all the processes necessary for the farm to work, while the Nodes only run a provider and adb. Affected devices are connected to a Node, but NEVER the server.

Device is listed ready-for-use in the devicefarms webGUI. You can open the details page, but the screen is grey and all the extra informations (like the connection URL) are void and empty. Also, you cannot leave the details page with the little red x above the (grey) screen any more. 

All the information required for this page to work should get pulled from the RethinkDB in the moment the user opens the Details page. But examining affected devices did show that the field ins the DB are empty at this point. Strangely, also this is true for devices which sill work sometimes. 

The wss String and all information necessary for filling out the necessary database fields (and later, the detail page) should be pulled from the device's provider connection process from within the docker container, where the provider is running. Said process exists, and all necessary information are not only available, but also valid (tested with the adb connection string). 

So... a device, which is attached properly and has all connection information available fails to show up in the WebGUI, if the Node its attached to experiences as less as one four seconds (not measured, but the average time in my reproduction environment, see reproduction) of  network off time. 

By itself, it will never recover; sometimes an usb-reset will do the trick, but most times I have to restart the provider on that Node. 

For a long time I thought the USB hubs were responsible for this, but it seems they do work fine. 

**Does it only happen on a specific device? Please run `adb devices -l` and paste the corresponding row.**

Every device not connected to the main server can be affected, usually multiple are affected at once (but not all, strangely). Of course, devices connected to the main Server are never affected (because they cannot experience a network disconnect from the perspective of their provider).

beside this I  did not notice any differences between different Android versions or phone vendors. if there are any, they do remain unknown. 

Also, we have a local stf branch with updated nodeJS (18.something?) and AngularJS at 1.8.3, which works fine... that has the same issue. 

**Please provide the steps to reproduce the issue.**

First, you need three three server in some form to reproduce that in the most realistic manner. May work with two (omit the Client). 

- The Server (where all devicefarm processes are running)
- The Node (where only adb and provider are running and the Phone for testing is attached
- The Client (where the webGUI is called from)
- The Device (the phone to test)

All of them should be able to find the others in their network. Can be done with VMs (I recommend VirtualBox 7.0.4 with NAT networks; 7.0.2 seems to be faulty) and physical devices. Our docker setup contains one Container for each stf process; I never tested that issue with the... normal all-STF-in-One setup you use here. its worth a try, but not now. 

Have the Server start all processes, than have the Node start up, attach the Device to the Node, and finally access the Device from the Client. Should work as expected.

Then leave for the devicelist, and disconnect the Node from your network. in my VM setup, I simply untick the device/network connection entry and re-tick it just right after that. This usually takes about four seconds. Pulling and plugging a network cable with physical servers should do the same (is tested and bug-verified).

Now open the Device in your Client. The Device's screen should be grey, and stuff like the connection sting should be lost. Nothing you can do to this device short of restarting the provider process at the Node can bring it back into an usable state. Sometimes, an usbreset will do too (which made me assume a faulty USB Hub first). 

**What is the expected behavior?**

It should either go offline, disconnected or just (which would be best) remain usable, or be renewed. I wish I could tell what part in the "gui -> db -> provider process" chain of getting the inforsmation is broken, but that I did not find out. 

**Do you see errors or warnings in the `stf local` output? If so, please paste them or the full log here.**

Absolutely no errors anywhere. Neither node nor server seem to be aware of the broken connection. Not even the Browser Debug shows a real error message, it just does not start the wss, because the db entry for the wss is empty. 

**Please run `stf doctor` and paste the output here.**

... we have one container for each stf process, which one is required? from the Server provider, this looks like that: 

```
2022-12-07T08:06:02.942Z INF/cli:doctor 19 [*] OS Arch: x64
2022-12-07T08:06:02.944Z INF/cli:doctor 19 [*] OS Platform: linux
2022-12-07T08:06:02.944Z INF/cli:doctor 19 [*] OS Platform: 5.15.0-56-generic
2022-12-07T08:06:02.945Z INF/cli:doctor 19 [*] Using Node 17.9.0
2022-12-07T08:06:02.969Z INF/cli:doctor 19 [*] Using ZeroMQ 4.2.2
2022-12-07T08:06:03.001Z ERR/cli:doctor 19 [*] RethinkDB is not installed (`rethinkdb` is missing)
2022-12-07T08:06:03.002Z ERR/cli:doctor 19 [*] ProtoBuf is not installed (`protoc` is missing)
2022-12-07T08:06:03.002Z ERR/cli:doctor 19 [*] ADB is not installed (`adb` is missing)
2022-12-07T08:06:03.134Z INF/cli:doctor 19 [*] Using GraphicsMagick 1.3.35
```

well... of course the rethinkDB and the adb are not in its container. And where to find the ProtoBuf?

** docker setup**

because its different, I guess you need at least the Server docker-compose.yml in here. The Node version is... not the same, but a reuse of it, by simply removing any service but the adb and provider and removing their now not fitting requirements. 
... of course, I cannot attach .yaml files here. WHYYYYY?
```

version: '3'

volumes:
  rethinkdb:
  storage-temp:

networks:
  db:
  internal:
  ldap:

services:
  ldapservice:
    command: --copy-service --loglevel debug
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_OPENLDAP}
    volumes:
      - ./ldap/data:/var/lib/ldap
      - ./ldap/conf:/etc/ldap/slapd.d
    networks:
      ldap:
    restart: unless-stopped
    environment:
      - LDAP_BASE_DN=dc=devicefarm,dc=hom
      - LDAP_ORGANISATION=HouseOfMobile
      - LDAP_DOMAIN=devicefarm.hom
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}

  ldapadminservice:
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_PHPLDAP}
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldapservice
      - PHPLDAPADMIN_HTTPS=true
    networks:
      internal:
      ldap:
    restart: unless-stopped
    depends_on:
      - ldapservice

  ldappss:
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_PSS}
    volumes:
      - ./pss/pss.conf.php:/var/www/conf/config.inc.local.php
      - ./images/STF-512.png:/var/www/html/images/logo.png
      - ./pss/pss-hom.css:/var/www/html/css/self-service-password.css
      - ./pss/en.inc.php:/var/www/lang/en.inc.php
      - ./pss/de.inc.php:/var/www/lang/de.inc.php
      - ./pss/footer.tpl:/var/www/templates/footer.tpl
    restart: unless-stopped
    depends_on:
      - ldapservice
    networks:
      internal:
      ldap:
    environment:
      - LDAP_BIND_PWD=${LDAP_ADMIN_PASSWORD}

  nginx:
          #build: nginx/
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_NGINX}
    #entrypoint: /bin/bash -c "while [ 1 ]; do sleep 1; done"
    volumes:
      - ./nginx/nginx-ssl.conf:/etc/nginx/templates/nginx.conf.devicefarm
      - ./nginx_certs/${NODE_NAME}.key:/etc/nginx/ssl/${NODE_NAME}.key:ro
      - ./nginx_certs/${NODE_NAME}.crt:/etc/nginx/ssl/${NODE_NAME}.crt:ro
      - ./nginx_certs/stf-dhparam.pem:/etc/nginx/ssl/stf-dhparam.pem:ro
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - NODE_NAME
    depends_on:
      - app
      - auth
      - storage-plugin-apk
      - storage-plugin-image
      - storage-temp
      - websocket
      - api
      - ldappss
      - ldapadminservice
    networks:
      internal:

  nginx-storage:
          #build: nginx/
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_NGINX}
    volumes:
      - ./nginx/nginx-storage.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    environment:
      - NODE_NAME
    depends_on:
      - app
      - auth
      - storage-plugin-apk
      - storage-plugin-image
      - storage-temp
      - websocket
      - api
    networks:
      internal:

  adb:
    #image: adb_test
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_ADB}
    restart: unless-stopped
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    networks:
      internal:

  rethinkdb:
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_RETHINK}
    #image: ${DOCKER_PROXY_PREFIX}rethinkdb:latest
    restart: unless-stopped
    volumes:
      - rethinkdb:/data
    ports:
      - 8080:8080
    networks:
      db:

  rethinkdb-log:
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_STF}
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
    command: stf log-rethinkdb --connect-sub tcp://triproxy:7150
    networks:
      internal:
      db:

  app:
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_STF}
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
    volumes:
      # Mount A4A Images
      - ./images/STF-512.png:/app/res/common/logo/exports/STF-512.png
      - ./images/afa-128.png:/app/res/common/logo/exports/STF-128.png
      - ./images/STF-512.png:/app/res/build/e831b7164c8a65b849691bff62cdb160.png
      # Mount customized MD files that might need to be changed during runtime
      #- ./pages/help.md:/app/helm.md
      #- ./pages/help.md:/app/node_modules/@devicefarmer/stf-wiki/[en]-Help.md
    command: stf app --auth-url https://${HOSTNAME}/auth/ldap/ --websocket-url wss://${HOSTNAME}/ --port 3000
    depends_on:
      - rethinkdb
      - auth
      - websocket
    networks:
      internal:
      db:

  auth:
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_STF}
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
      - STF_AUTH_LDAP_LDAP_URL=ldap://ldapservice
      - STF_AUTH_LDAP_LDAP_SEARCH_DN=dc=devicefarm,dc=hom
      - STF_AUTH_LDAP_LDAP_SEARCH_FIELD=userid
      - STF_AUTH_LDAP_LDAP_BIND_DN=cn=admin,dc=devicefarm,dc=hom
      - STF_AUTH_LDAP_LDAP_BIND_CREDENTIALS=${LDAP_ADMIN_PASSWORD}
    command: stf auth-ldap --app-url https://${HOSTNAME}/ --port 3000
    depends_on:
      - rethinkdb
    networks:
      internal:
      db:
      ldap:

  processor:
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_STF}
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
    command: stf processor --connect-app-dealer tcp://triproxy:7160 --connect-dev-dealer tcp://dev-triproxy:7260
    depends_on:
      - rethinkdb
      - triproxy
      - dev-triproxy
    networks:
      internal:
      db:

  triproxy:
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_STF}
    restart: unless-stopped
    command: stf triproxy app --bind-pub "tcp://*:7150" --bind-dealer "tcp://*:7160" --bind-pull "tcp://*:7170"
    ports:
      - 7150:7150
      - 7170:7170
    networks:
      internal:

  dev-triproxy:
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_STF}
    restart: unless-stopped
    command: stf triproxy dev --bind-pub "tcp://*:7250" --bind-dealer "tcp://*:7260" --bind-pull "tcp://*:7270"
    ports:
      - 7250:7250
      - 7270:7270
    networks:
      internal:

  migrate:
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_STF}
    environment:
      - RETHINKDB_PORT_28015_TCP
      - STF_ADMIN_NAME
      - STF_ADMIN_EMAIL
    command: stf migrate
    depends_on:
      - rethinkdb
    networks:
      db:

  provider:
          #image: stf_test
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_STF}
    restart: unless-stopped
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    command: stf provider --name ${NODE_NAME} --connect-sub tcp://${PROVIDER_CONNECT}:7250 --connect-push tcp://${PROVIDER_CONNECT}:7270 --storage-url https://${PROVIDER_CONNECT}/ --public-ip ${HOSTNAME} --heartbeat-interval 10000 --screen-ws-url-pattern "wss://${PROVIDER_CONNECT}/d/${NODE_NAME}/<%= serial %>/<%= publicPort %>/" --adb-host adb --min-port 7400 --max-port 7700 --allow-remote
    ports:
      - 7400-7700:7400-7700
    depends_on:
      - adb
        #      - dev-triproxy
        #      - triproxy
        #      - storage-temp
    networks:
      internal:

  reaper:
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_STF}
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
    depends_on:
      - migrate
      - rethinkdb
      - dev-triproxy
      - triproxy
    command: stf reaper dev --connect-push tcp://dev-triproxy:7270 --connect-sub tcp://triproxy:7150 --heartbeat-timeout 30000
    networks:
      internal:
      db:

  storage-plugin-apk:
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_STF}
    restart: unless-stopped
    command: stf storage-plugin-apk --port 3000 --storage-url http://storage-temp:3000/
    depends_on:
      - storage-temp
    networks:
      internal:

  storage-plugin-image:
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_STF}
    restart: unless-stopped
    command: stf storage-plugin-image --port 3000 --storage-url http://storage-temp:3000/
    depends_on:
      - storage-temp
    networks:
      internal:

  storage-temp:
          #build: storage-temp/
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_STF}
    restart: unless-stopped
    volumes:
      - storage-temp:/app/data
    ports:
      - 3000:3000
    command: stf storage-temp --port 3000 --save-dir /app/data
    networks:
      internal:

  websocket:
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_STF}
    restart: unless-stopped
    environment:
      - SECRET
      - RETHINKDB_PORT_28015_TCP
    command: stf websocket --port 3000 --storage-url http://storage-temp:3000/ --connect-sub tcp://triproxy:7150 --connect-push tcp://triproxy:7170
    depends_on:
      - migrate
      - rethinkdb
      - storage-temp
      - triproxy
      - dev-triproxy
    networks:
      internal:
      db:

  api:
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_STF}
    restart: unless-stopped
    environment:
      - SECRET
      - RETHINKDB_PORT_28015_TCP
    command: stf api --port 3000 --connect-sub tcp://triproxy:7150 --connect-push tcp://triproxy:7170 --connect-sub-dev tcp://dev-triproxy:7250 --connect-push-dev tcp://dev-triproxy:7270
    depends_on:
      - migrate
      - rethinkdb
      - triproxy
    networks:
      internal:
      db:

  groups-engine:
    image: ${DOCKER_PROXY_PREFIX}${IMAGE_STF}
    restart: unless-stopped
    environment:
      - SECRET
      - RETHINKDB_PORT_28015_TCP
    command: stf groups-engine --connect-sub tcp://triproxy:7150 --connect-push tcp://triproxy:7170 --connect-sub-dev tcp://dev-triproxy:7250 --connect-push-dev tcp://dev-triproxy:7270
    depends_on:
      - migrate
      - rethinkdb
      - triproxy
      - dev-triproxy
    networks:
      internal:
      db:

```
