### ISSUE TITLE
stf-app unable to connect to rethinkdb:28015

### ISSUE THREAD

**Issue by ttork354** [DeviceFarmer/stf#716]
Super hi for all!

Please help solved this puzzle
I have 2 machince with static ip - Windows 11 **192.168.0.249** (rethinkdb) and Ubuntu server 22.04.3 **192.168.0.129** (stf)
Then i run stf docker-compose.yaml stf-app container unable to connect to rethinkdb:28015

Let's look at what we have:

1. Running rethinkdb:2.4.2 on Windows 11 via **docker-compose.yaml** like this
```
version: '3.8'

services:
  rethinkdb:
    image: rethinkdb:2.4.2
    container_name: rethinkdb
    restart: always
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    command: "rethinkdb --bind all --canonical-address 192.168.0.249 --cache-size 2048 --initial-password stf"
    volumes:
      - c:\rethinkdb\data:/data

volumes:
  rethinkdb_data:
```
rethinkdb accessable http://192.168.0.249:8080/

2. Running part of stf on Ubuntu server 22.04.3 via **docker-compose.yaml** like this:
(I’m launching partly because of testing and going through [DEPLOYMENT.md](https://github.com/DeviceFarmer/stf/blob/master/doc/DEPLOYMENT.md) step by step)
```
version: '3.8'
services:

  adbd:
    container_name: adbd
    image: 'devicefarmer/adb:latest'
    restart: unless-stopped
    ports:
      - "5037:5037"
    volumes:
      - '/dev/bus/usb:/dev/bus/usb'
    privileged: true

  rethinkdb-proxy-28015:
    container_name: rethinkdb-proxy-28015
    image: 'devicefarmer/ambassador:latest'
    restart: unless-stopped
    ports:
      - '28015:28015'
    environment:
      - AUTHKEY=stf
      - RETHINKDB_PORT_28015_TCP=tcp://192.168.0.249:28015

  stf-app:
    depends_on: [rethinkdb-proxy-28015]
    container_name: stf-app
    image: 'devicefarmer/stf:latest'
    restart: unless-stopped
    ports:
      - '3100:3000'
    environment:
      - SECRET=secret
    links:
      - 'rethinkdb-proxy-28015:rethinkdb'
    command: 'stf app --port 3000 --auth-url http://192.168.0.129/auth/mock --websocket-url http://192.168.0.129/'
```

My `docker compose up` output looks like this

```
[+] Running 3/3
 ✔ Container rethinkdb-proxy-28015  Created                                                                                                                                           0.0s
 ✔ Container adbd                   Created                                                                                                                                           0.0s
 ✔ Container stf-app                Created                                                                                                                                           0.1s
Attaching to adbd, rethinkdb-proxy-28015, stf-app
adbd                   | 10-13 15:13:59.127     7     7 I adb     : auth.cpp:416 adb_auth_init...
adbd                   | 10-13 15:13:59.127     7     7 I adb     : auth.cpp:152 loaded new key from '/root/.android/adbkey' with fingerprint 9BB6C5623F63CB10053006DE7335A39BE64999A41891CDE4A8B03F39BD3F9135
adbd                   | 10-13 15:13:59.127     7     7 I adb     : auth.cpp:391 adb_auth_inotify_init...
adbd                   | 10-13 15:13:59.276     7    14 I adb     : transport.cpp:307 4427f628: write thread spawning
adbd                   | 10-13 15:13:59.276     7    13 I adb     : transport.cpp:335 4427f628: read thread spawning
adbd                   | 10-13 15:13:59.286     7     7 I adb     : transport.cpp:1727 fetching keys for transport 4427f628
adbd                   | 10-13 15:13:59.286     7     7 I adb     : auth.cpp:468 Calling send_auth_response
adbd                   | 10-13 15:13:59.299     7     7 I adb     : adb.cpp:179 4427f628: offline
stf-app                | 2023-10-13T15:13:59.822Z INF/app 1 [*] Using pre-built resources
stf-app                | 2023-10-13T15:13:59.830Z INF/app 1 [*] Listening on port 3000
stf-app                | 2023-10-13T15:13:59.831Z INF/db 1 [*] Connecting to 127.0.0.1:28015
stf-app                | 2023-10-13T15:13:59.836Z INF/db 1 [*] Unable to connect to 127.0.0.1:28015
stf-app                | 2023-10-13T15:13:59.836Z FTL/db 1 [*] No hosts left to try
stf-app                | 2023-10-13T15:13:59.837Z FTL/util:lifecycle 1 [*] Shutting down due to fatal error
stf-app exited with code 0
```

I dont understand - why **stf-app** cant access to **rethinkdb** via **rethinkdb-proxy-28015**
Maybe something wrong with rethinkdb-proxy-28015 container?

If netcating or telneting windows port 28015 from ubuntu - everything its allright
```
root@stf:/home/stf/stf-separate-service# nc -zv 192.168.0.249 28015
Connection to 192.168.0.249 28015 port [tcp/*] succeeded!
```

```
root@stf:/home/stf/stf-separate-service# telnet 192.168.0.249 28015
Trying 192.168.0.249...
Connected to 192.168.0.249.
Escape character is '^]'.
^CConnection closed by foreign host.
```
What did I miss?

**Comment by denis99999** [comment]
@ttork354 , 
Your configuration seems good, I don't know what is wrong at first glance, perhaps it is due to your Docker version at Ubuntu server side, I know links behave differently with the introduction of the Docker networks feature (cf. [Docker Legacy container links](https://docs.docker.com/network/links/)), so I recommend you to switch to another solution if you are blocked, for example you could do these changes in your docker-compose file:
- remove the `rethinkdb-proxy-28015` service
- remove the `links` and `depends_on` parts of the `stf-app` service
- add the environment variable `RETHINKDB_PORT_28015_TCP=tcp://192.168.0.249:28015` into your `stf-app` service in order to point directly to the external rethinkdb server

So, your docker-compose file should be something like that:

```
version: '3.8'
services:

  adbd:
    container_name: adbd
    image: 'devicefarmer/adb:latest'
    restart: unless-stopped
    ports:
      - "5037:5037"
    volumes:
      - '/dev/bus/usb:/dev/bus/usb'
    privileged: true

  stf-app:
    container_name: stf-app
    image: 'devicefarmer/stf:latest'
    restart: unless-stopped
    ports:
      - '3100:3000'
    environment:
      - SECRET=secret
      - RETHINKDB_PORT_28015_TCP=tcp://192.168.0.249:28015
    command: 'stf app --port 3000 --auth-url http://192.168.0.129/auth/mock --websocket-url http://192.168.0.129/'
```
I think it should works!
