### ISSUE TITLE
STF on docker cannot connect to the device

### ISSUE THREAD

**Issue by tuyenlq** [DeviceFarmer/stf#719]
Hi team,

 I have problem with my STF on docker, I have installed it successfully but I don't see the device.

Docker version 24.0.7, build afdd53b  - Ubuntu 20.04.6 LTS

How do I configure it?

Thanks
![image](https://github.com/DeviceFarmer/stf/assets/10045154/f33b79b8-494c-489e-89b1-b790497c1c15)

Log adb on docker 

```
 2023-10-28 12:30:20 adb I 10-28 05:30:20     7     7 adb_auth_host.cpp:416] adb_auth_init...
2023-10-28 12:30:20 adb I 10-28 05:30:20     7     7 adb_auth_host.cpp:174] read_key_file '/root/.android/adbkey'...
2023-10-28 12:30:20 adb I 10-28 05:30:20     7     7 adb_auth_host.cpp:391] adb_auth_inotify_init...
2023-10-28 13:20:09 adb I 10-28 06:20:09     7     7 adb_auth_host.cpp:416] adb_auth_init...
2023-10-28 13:20:09 adb I 10-28 06:20:09     7     7 adb_auth_host.cpp:174] read_key_file '/root/.android/adbkey'...
2023-10-28 13:20:09 adb I 10-28 06:20:09     7     7 adb_auth_host.cpp:391] adb_auth_inotify_init...
```

docker-compose.yml

```
version: '3'

volumes:
  rethinkdb:
  storage-temp:

services:
  nginx:
    build: nginx/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - app
      - auth
      - storage-plugin-apk
      - storage-plugin-image
      - storage-temp
      - websocket
      - api
  adb:
    image: sorccu/adb:latest
    restart: unless-stopped
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
  rethinkdb:
    image: rethinkdb:2.4
    restart: unless-stopped
    volumes:
      - rethinkdb:/data
  app:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
    command: stf app --auth-url http://${PUBLIC_IP}/auth/mock/ --websocket-url ws://${PUBLIC_IP}/ --port 3000
    depends_on:
      - rethinkdb
      - auth
      - websocket
  auth:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
      - SECRET
    command: stf auth-mock --app-url http://${PUBLIC_IP}/ --port 3000
    depends_on:
      - rethinkdb
  processor:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
    command: stf processor --connect-app-dealer tcp://triproxy:7160 --connect-dev-dealer tcp://dev-triproxy:7260
    depends_on:
      - rethinkdb
      - triproxy
      - dev-triproxy
  triproxy:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    command: stf triproxy app --bind-pub "tcp://*:7150" --bind-dealer "tcp://*:7160" --bind-pull "tcp://*:7170"
  dev-triproxy:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    command: stf triproxy dev --bind-pub "tcp://*:7250" --bind-dealer "tcp://*:7260" --bind-pull "tcp://*:7270"
  migrate:
    image: devicefarmer/stf:latest
    environment:
      - RETHINKDB_PORT_28015_TCP
    command: stf migrate
    depends_on:
      - rethinkdb
  provider:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    command: stf provider --name ${STATION_NAME} --connect-sub tcp://dev-triproxy:7250 --connect-push tcp://dev-triproxy:7270 --storage-url http://${PUBLIC_IP}/ --public-ip ${PUBLIC_IP} --heartbeat-interval 10000 --screen-ws-url-pattern "ws://${PUBLIC_IP}/d/nuc/<%= serial %>/<%= publicPort %>/" --adb-host adb --min-port 7400 --max-port 7700 --allow-remote
    ports:
      - 7400-7700:7400-7700
    depends_on:
      - adb
      - dev-triproxy
      - triproxy
      - storage-temp
  reaper:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    environment:
      - RETHINKDB_PORT_28015_TCP
    depends_on:
      - migrate
      - rethinkdb
      - dev-triproxy
      - triproxy
    command: stf reaper dev --connect-push tcp://dev-triproxy:7270 --connect-sub tcp://triproxy:7150 --heartbeat-timeout 30000
  storage-plugin-apk:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    command: stf storage-plugin-apk --port 3000 --storage-url http://${PUBLIC_IP}/
    depends_on:
      - storage-temp
  storage-plugin-image:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    command: stf storage-plugin-image --port 3000 --storage-url http://${PUBLIC_IP}/
    depends_on:
      - storage-temp
  storage-temp:
    build: storage-temp/
    restart: unless-stopped
    volumes:
      - storage-temp:/app/data
    command: stf storage-temp --port 3000 --save-dir /app/data
  websocket:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    environment:
      - SECRET
      - RETHINKDB_PORT_28015_TCP
    command: stf websocket --port 3000 --storage-url http://${PUBLIC_IP}/ --connect-sub tcp://triproxy:7150 --connect-push tcp://triproxy:7170
    depends_on:
      - migrate
      - rethinkdb
      - storage-temp
      - triproxy
      - dev-triproxy
  api:
    image: devicefarmer/stf:latest
    restart: unless-stopped
    environment:
      - SECRET
      - RETHINKDB_PORT_28015_TCP
    command: stf api --port 3000 --connect-sub tcp://triproxy:7150 --connect-push tcp://triproxy:7170 --connect-sub-dev tcp://dev-triproxy:7250 --connect-push-dev tcp://dev-triproxy:7270
    depends_on:
      - migrate
      - rethinkdb
      - triproxy
```
