### ISSUE TITLE
Remote Debug not working

### ISSUE THREAD

**Issue by hajoha** [DeviceFarmer/stf#806]
**What issue or idea are you experiencing?**
I am attempting to use the remote debug feature, but it's not functioning as expected.

**Does this issue occur on a specific device? Please run `adb devices -l` and share the relevant output.**

This issue affects all devices.

**Steps to reproduce the issue:**

1. Use the Docker Compose file to set up the environment.
2. Connect the device to the STF machine via USB.
3. Deploy the ADB key on the STF through the web GUI.
4. On my machine, run `adb connect 192.168.213.230:7421`.

**What is the expected behavior?**
running `adb devices -l` on my machine should display available devices.
But its showing:
```
mymachine:/opt/omnt-github$ adb devices -l
List of devices attached
192.168.213.230:7421   offline transport_id:1
```

**Are there any errors or warnings in the `stf local` output? If so, please paste them here.**
Yes, the output shows repeated ADB connection attempts:

```
stf        | 2024-08-22T11:28:46.718Z INF/device:plugins:connect 252 [R5CW22DXGSY] New remote ADB connection from ::ffff:10.147.66.245
stf        | 2024-08-22T11:28:46.985Z INF/device:plugins:connect 252 [R5CW22DXGSY] New remote ADB connection from ::ffff:10.147.66.245
...
```

**Please run `stf doctor` and paste the output here.**
```
stf@14ae0cecb2ab:/app$ stf doctor
2024-08-22T11:29:33.011Z INF/cli:doctor 447 [*] OS Arch: x64
2024-08-22T11:29:33.013Z INF/cli:doctor 447 [*] OS Platform: linux
2024-08-22T11:29:33.013Z INF/cli:doctor 447 [*] OS Platform: 6.8.0-41-generic
2024-08-22T11:29:33.013Z INF/cli:doctor 447 [*] Using Node 17.9.0
2024-08-22T11:29:33.024Z INF/cli:doctor 447 [*] Using ZeroMQ 4.2.2
2024-08-22T11:29:33.038Z ERR/cli:doctor 447 [*] RethinkDB is not installed (`rethinkdb` is missing)
2024-08-22T11:29:33.039Z ERR/cli:doctor 447 [*] ProtoBuf is not installed (`protoc` is missing)
2024-08-22T11:29:33.039Z ERR/cli:doctor 447 [*] ADB is not installed (`adb` is missing)
2024-08-22T11:29:33.040Z INF/cli:doctor 447 [*] Using GraphicsMagick 1.3.35
```

I have verified that both my machine and the STF machine are using the same version of ADB.

**ADB Version on My Machine:**
```
mymachine:/opt$ adb version
Android Debug Bridge version 1.0.41
Version 35.0.1-11580240
Installed as /home/myuser/Android/Sdk/platform-tools/adb
Running on Linux 6.8.0-40-generic (x86_64)
```

**ADB Version on STF Machine:**
```
c605788827f1:/# adb version
Android Debug Bridge version 1.0.41
Version 35.0.1-11580240
Installed as /opt/platform-tools/adb
Running on Linux 6.8.0-41-generic (x86_64)
```

I have already tried power cycling all the devices involved.

# docker-compose 
```
services:
  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb:2.4.2
    restart: unless-stopped
    volumes:
        - "rethinkdb-data:/data"
    command: "rethinkdb --bind all --cache-size 2048"

  adb:
    container_name: adb
    image: devicefarmer/adb:latest
    restart: unless-stopped
    volumes: 
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true

  stf:
    container_name: stf
    image: devicefarmer/stf
    ports:
      - "7100:7100"
      - "7110:7110"
      - "7400-7500:7400-7500"
    environment:
      - TZ='America/Los_Angeles'
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_ADMIN_EMAIL=<YOUR_EMAIL>
      - STF_ADMIN_NAME=<YOUR_NAME>
    restart: unless-stopped
    command: stf local --allow-remote --adb-host adb --public-ip 192.168.213.230 --provider-min-port 7400 --provider-max-port 7500

volumes:
  rethinkdb-data: {}
```
